sudo: required

services:
  - docker

language: bash

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - bash ./build.sh ${arch} 1.10.1

env:
  - arch=x86_64
  - arch=armv7l
  - arch=aarch64
  - arch=amazonlinux
